name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify your Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install -r requirements.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests
      run: |
        pytest  # Ensure you have test files configured

    # - name: Deploy (Optional)
    #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    #   run: echo "Deploying the application..."  # Add deployment steps if necessary
